import { Enzyme } from './models/Enzyme';
import { ReactionStep } from './models/ReactionStep';

const enzymes = {
  hexokinase: new Enzyme({
    id: 'hexokinase',
    name: 'Hexokinase',
    description: 'Transfers the gamma phosphate of ATP to glucose and traps glucose intracellularly.',
    activeSite: [0, 0.45, 0],
    regulatoryRole: 'Entry gate',
    catalyticNote: 'Mg2+ coordinates ATP while the C6 hydroxyl performs nucleophilic attack on the terminal phosphate.',
    aliases: ['Glucokinase (liver/pancreas isoform)'],
    regulation: 'Biology Online notes hexokinase is inhibited by G6P, while glucokinase is an insulin-inducible liver/pancreas isoform not inhibited by G6P.',
    articleSummary: 'The article treats this as the first irreversible, flux-generating trapping step because G6P cannot freely cross the membrane.',
  }),
  pgi: new Enzyme({
    id: 'pgi',
    name: 'Phosphoglucose isomerase',
    description: 'Rearranges the carbonyl position from an aldose to a ketose.',
    activeSite: [0, 0.2, 0],
    catalyticNote: 'The ring opens, an enediol intermediate forms, and the ketose scaffold recloses as fructose-6-phosphate.',
    aliases: ['Phosphohexose isomerase'],
    articleSummary: 'Biology Online names the catalyst phosphohexose isomerase while describing the same G6P-to-F6P rearrangement.',
  }),
  pfk: new Enzyme({
    id: 'pfk',
    name: 'Phosphofructokinase-1',
    description: 'Commits carbon to glycolysis with a second ATP-dependent phosphorylation.',
    activeSite: [0, 0.5, 0],
    regulatoryRole: 'Main control switch',
    catalyticNote: 'ATP donates a phosphate to C1, creating a highly activated bisphosphate and locking flux into glycolysis.',
    regulation: 'The article highlights PFK-1 as the bottleneck: AMP and fructose-2,6-bisphosphate activate it, while ATP, citrate, and low pH inhibit it.',
    articleSummary: 'Biology Online emphasizes that this is the rate-limiting, first committed, irreversible bottleneck step and notes Mg++ as the cofactor.',
  }),
  aldolase: new Enzyme({
    id: 'aldolase',
    name: 'Aldolase',
    description: 'Cleaves fructose-1,6-bisphosphate into two three-carbon fragments.',
    activeSite: [0, 0.3, 0],
    catalyticNote: 'A Schiff-base assisted cleavage breaks the C3-C4 bond, yielding DHAP and G3P.',
    articleSummary: 'The article groups the aldolase split together with the observation that triose phosphate isomerase can interconvert DHAP and G3P.',
  }),
  tpi: new Enzyme({
    id: 'tpi',
    name: 'Triose phosphate isomerase',
    description: 'Interconverts DHAP and G3P so both carbons feed the payoff phase.',
    activeSite: [0, 0.2, 0],
    catalyticNote: 'Catalysis proceeds through an enediol intermediate, channeling DHAP into the productive G3P stream.',
    aliases: ['Phosphotriose isomerase'],
    articleSummary: 'Biology Online discusses triose phosphate isomerase during the splitting section rather than giving it a separate numbered step.',
  }),
  gapdh: new Enzyme({
    id: 'gapdh',
    name: 'Glyceraldehyde-3-phosphate dehydrogenase',
    description: 'Oxidizes G3P and captures electrons in NADH while adding inorganic phosphate.',
    activeSite: [0, 0.4, 0],
    catalyticNote: 'Hydride transfer to NAD+ is coupled to formation of the high-energy acyl phosphate in 1,3-BPG.',
    articleSummary: 'The article explicitly notes consumption of inorganic phosphate and reduction of NAD+ to NADH + H+ in this transition.',
  }),
  pgk: new Enzyme({
    id: 'pgk',
    name: 'Phosphoglycerate kinase',
    description: 'Performs substrate-level phosphorylation from 1,3-BPG to ADP.',
    activeSite: [0, 0.35, 0],
    catalyticNote: 'The acyl phosphate directly transfers to ADP, producing the first ATP molecules of glycolysis.',
    aliases: ['Phosphoglycerate kinase', '1,3BPG kinase'],
    articleSummary: 'Biology Online calls this the only reversible kinase step and highlights substrate-level phosphorylation here.',
  }),
  pgm: new Enzyme({
    id: 'pgm',
    name: 'Phosphoglycerate mutase',
    description: 'Repositions the phosphate from carbon 3 to carbon 2.',
    activeSite: [0, 0.2, 0],
    catalyticNote: 'A phospho-enzyme intermediate temporarily holds the phosphate while it is relocated internally.',
    articleSummary: 'The article presents this as a straightforward phosphoglycerate mutase shift from 3PG to 2PG.',
  }),
  enolase: new Enzyme({
    id: 'enolase',
    name: 'Enolase',
    description: 'Removes water to generate the high-energy enol phosphate PEP.',
    activeSite: [0, 0.3, 0],
    catalyticNote: 'Dehydration installs the enol phosphate geometry that makes PEP one of the highest-energy metabolites in the cell.',
    articleSummary: 'Biology Online specifically calls out water release in the enolase step.',
  }),
  pyruvateKinase: new Enzyme({
    id: 'pyruvate-kinase',
    name: 'Pyruvate kinase',
    description: 'Transfers phosphate from PEP to ADP to generate pyruvate and ATP.',
    activeSite: [0, 0.42, 0],
    regulatoryRole: 'Exit gate',
    catalyticNote: 'Phosphate transfer is followed by collapse of the enol to the stable keto pyruvate product.',
    regulation: 'The article notes liver pyruvate kinase is inhibited by glucagon/epinephrine-driven phosphorylation, unlike the muscle enzyme.',
    articleSummary: 'Biology Online highlights this as the second substrate-level phosphorylation and the pyruvate-forming endpoint.',
  }),
};

const substrate = (template, copies = 1) => ({ template, copies, role: 'substrate' });
const product = (template, copies = 1) => ({ template, copies, role: 'product' });
const cofactor = (template, direction = 'support', copies = 1) => ({
  template,
  direction,
  copies,
  role: 'cofactor',
});

export const glycolysisSteps = [
  new ReactionStep({
    id: 'gly-1',
    index: 0,
    title: 'Glucose -> Glucose-6-phosphate',
    stage: 'investment',
    summary: 'Hexokinase uses ATP to phosphorylate the C6 hydroxyl and trap glucose inside the cell.',
    substrates: [substrate('glucose')],
    products: [product('g6p')],
    enzyme: enzymes.hexokinase,
    cofactors: [cofactor('atp', 'consume'), cofactor('adp', 'release'), cofactor('mg', 'support')],
    mechanism: [
      'Glucose docks so the C6 hydroxyl faces ATP inside the active site.',
      'Mg2+ neutralizes negative charge around the phosphate chain.',
      'The gamma phosphate transfers from ATP to glucose, producing glucose-6-phosphate.',
    ],
    energyDelta: { atp: -1, nadh: 0 },
    notes: ['Irreversible under physiological conditions', 'First ATP investment'],
    regulatory: true,
    articleStepLabel: 'Biology Online Step 1',
    articleSummary: 'Reviewed against the article: first irreversible trapping step, described there as a flux-generating entry into downstream metabolism.',
    camera: {
      focus: [0, 0.45, 0],
      offset: [4.6, 5.8, 16.4],
    },
  }),
  new ReactionStep({
    id: 'gly-2',
    index: 1,
    title: 'Glucose-6-phosphate -> Fructose-6-phosphate',
    stage: 'investment',
    summary: 'Phosphoglucose isomerase repositions the carbonyl from C1 to C2 through ring opening and reclosing.',
    substrates: [substrate('g6p')],
    products: [product('f6p')],
    enzyme: enzymes.pgi,
    mechanism: [
      'The ring opens to expose the aldose chain.',
      'A transient enediol rearrangement shifts the carbonyl to C2.',
      'The ketose form closes into fructose-6-phosphate.',
    ],
    notes: ['Reversible rearrangement', 'Prepares carbon skeleton for symmetric cleavage later'],
    articleStepLabel: 'Biology Online Step 2',
    articleSummary: 'The article describes this simply as G6P conversion to F6P by phosphohexose isomerase.',
    camera: {
      focus: [0, 0.2, 0],
      offset: [4.4, 5.4, 16],
    },
  }),
  new ReactionStep({
    id: 'gly-3',
    index: 2,
    title: 'Fructose-6-phosphate -> Fructose-1,6-bisphosphate',
    stage: 'investment',
    summary: 'PFK-1 commits the pathway by adding a second phosphate at C1 using ATP.',
    substrates: [substrate('f6p')],
    products: [product('f16bp')],
    enzyme: enzymes.pfk,
    cofactors: [cofactor('atp', 'consume'), cofactor('adp', 'release')],
    mechanism: [
      'F6P aligns with ATP in the phosphofructokinase active site.',
      'ATP donates a phosphate to C1, creating the bisphosphate.',
      'The activated product exits as the committed glycolytic intermediate.',
    ],
    energyDelta: { atp: -1, nadh: 0 },
    notes: ['Rate-limiting control step', 'Highly regulated by cellular energy charge'],
    regulatory: true,
    articleStepLabel: 'Biology Online Step 3',
    articleSummary: 'Reviewed against the article: Mg++-dependent, irreversible, rate-limiting, committed bottleneck into glycolysis.',
    camera: {
      focus: [0, 0.5, 0],
      offset: [4.8, 5.9, 16.6],
    },
  }),
  new ReactionStep({
    id: 'gly-4',
    index: 3,
    title: 'Fructose-1,6-bisphosphate -> DHAP + G3P',
    stage: 'investment',
    summary: 'Aldolase cleaves the activated six-carbon sugar into two three-carbon fragments.',
    substrates: [substrate('f16bp')],
    products: [product('dhap'), product('g3p')],
    enzyme: enzymes.aldolase,
    mechanism: [
      'The enzyme stabilizes the bisphosphate and polarizes the central bond.',
      'The C3-C4 bond breaks, releasing two triose phosphates.',
      'DHAP and G3P diffuse apart as separate product streams.',
    ],
    notes: ['Carbon split event', 'Creates the branching point before the duplicate payoff phase'],
    articleStepLabel: 'Biology Online Step 4',
    articleSummary: 'The article combines the aldolase cleavage with a note that triose phosphate isomerase can interconvert DHAP and G3P.',
    camera: {
      focus: [0, 0.3, 0],
      offset: [4.5, 5.6, 16.2],
    },
  }),
  new ReactionStep({
    id: 'gly-5',
    index: 4,
    title: 'DHAP -> G3P',
    stage: 'investment',
    summary: 'Triose phosphate isomerase converts DHAP into a second G3P, creating two parallel G3P streams.',
    substrates: [substrate('dhap')],
    products: [product('g3p', 2)],
    enzyme: enzymes.tpi,
    mechanism: [
      'DHAP opens into a reactive linear intermediate.',
      'Catalytic acid-base chemistry forms an enediol.',
      'The intermediate resolves into glyceraldehyde-3-phosphate, doubling the productive stream.',
    ],
    notes: ['End of investment phase', 'All subsequent reactions occur twice per glucose'],
    articleStepLabel: 'Article note folded into Step 4',
    articleSummary: 'Biology Online does not number this as a separate step, so the app keeps the classic 10-step convention while preserving the article’s 9-step numbering in the annotations.',
    camera: {
      focus: [0, 0.2, 0],
      offset: [4.4, 5.5, 16.1],
    },
  }),
  new ReactionStep({
    id: 'gly-6',
    index: 5,
    title: '2 G3P -> 2 1,3-Bisphosphoglycerate',
    stage: 'payoff',
    summary: 'Each G3P is oxidized and phosphorylated, transferring electrons to NAD+ and producing two NADH.',
    substrates: [substrate('g3p', 2)],
    products: [product('bpg13', 2)],
    enzyme: enzymes.gapdh,
    cofactors: [cofactor('nad', 'consume', 2), cofactor('nadh', 'release', 2), cofactor('pi', 'consume', 2)],
    mechanism: [
      'The aldehyde of each G3P is oxidized inside the dehydrogenase active site.',
      'Hydride transfer reduces NAD+ to NADH with a visible redox glow.',
      'Inorganic phosphate captures the oxidized intermediate to form 1,3-BPG.',
    ],
    energyDelta: { atp: 0, nadh: 2 },
    notes: ['First electron capture step', 'Everything shown here happens twice per original glucose'],
    articleStepLabel: 'Biology Online Step 5',
    articleSummary: 'The article emphasizes inorganic phosphate uptake and NAD+ reduction to NADH + H+ during this step.',
    repeatCount: 2,
    camera: {
      focus: [0, 0.42, 0],
      offset: [4.8, 5.8, 16.8],
    },
  }),
  new ReactionStep({
    id: 'gly-7',
    index: 6,
    title: '2 1,3-BPG -> 2 3-Phosphoglycerate',
    stage: 'payoff',
    summary: 'Phosphoglycerate kinase performs substrate-level phosphorylation to generate the first two ATP.',
    substrates: [substrate('bpg13', 2)],
    products: [product('pg3', 2)],
    enzyme: enzymes.pgk,
    cofactors: [cofactor('adp', 'consume', 2), cofactor('atp', 'release', 2)],
    mechanism: [
      'The acyl phosphate on 1,3-BPG aligns with ADP.',
      'Direct phosphate transfer generates ATP without a membrane or electron transport chain.',
      'The product relaxes into 3-phosphoglycerate after the high-energy phosphate is removed.',
    ],
    energyDelta: { atp: 2, nadh: 0 },
    notes: ['First ATP payoff step', 'Balances the two ATP spent earlier'],
    articleStepLabel: 'Biology Online Step 6',
    articleSummary: 'Reviewed against the article: first substrate-level phosphorylation and the only reversible kinase step in the pathway.',
    repeatCount: 2,
    camera: {
      focus: [0, 0.35, 0],
      offset: [4.6, 5.7, 16.4],
    },
  }),
  new ReactionStep({
    id: 'gly-8',
    index: 7,
    title: '2 3-Phosphoglycerate -> 2 2-Phosphoglycerate',
    stage: 'payoff',
    summary: 'Phosphoglycerate mutase shifts the phosphate internally from carbon 3 to carbon 2.',
    substrates: [substrate('pg3', 2)],
    products: [product('pg2', 2)],
    enzyme: enzymes.pgm,
    mechanism: [
      'A catalytic phosphate is briefly shared with the substrate.',
      'The original phosphate is relocated to C2.',
      'The enzyme is regenerated and 2-phosphoglycerate is released.',
    ],
    notes: ['Internal rearrangement', 'Primes the molecule for dehydration'],
    articleStepLabel: 'Biology Online Step 7',
    articleSummary: 'The article treats this as the phosphoglycerate mutase relocation from 3PG to 2PG.',
    repeatCount: 2,
    camera: {
      focus: [0, 0.2, 0],
      offset: [4.5, 5.5, 16.2],
    },
  }),
  new ReactionStep({
    id: 'gly-9',
    index: 8,
    title: '2 2-Phosphoglycerate -> 2 PEP',
    stage: 'payoff',
    summary: 'Enolase removes water to create the high-energy enol phosphate phosphoenolpyruvate.',
    substrates: [substrate('pg2', 2)],
    products: [product('pep', 2), product('water', 2)],
    enzyme: enzymes.enolase,
    mechanism: [
      'Hydrogen and hydroxyl are abstracted from adjacent carbons.',
      'Water leaves the substrate as a distinct product.',
      'The remaining scaffold collapses into the high-energy enol phosphate PEP.',
    ],
    notes: ['Dehydration step', 'Builds the highest phosphate-transfer potential in glycolysis'],
    articleStepLabel: 'Biology Online Step 8',
    articleSummary: 'The article explicitly flags this as the water-releasing enolase reaction that creates PEP.',
    repeatCount: 2,
    camera: {
      focus: [0, 0.3, 0],
      offset: [4.7, 5.6, 16.4],
    },
  }),
  new ReactionStep({
    id: 'gly-10',
    index: 9,
    title: '2 PEP -> 2 Pyruvate',
    stage: 'payoff',
    summary: 'Pyruvate kinase transfers phosphate to ADP, generating ATP and letting the enol collapse into stable pyruvate.',
    substrates: [substrate('pep', 2)],
    products: [product('pyruvate', 2)],
    enzyme: enzymes.pyruvateKinase,
    cofactors: [cofactor('adp', 'consume', 2), cofactor('atp', 'release', 2)],
    mechanism: [
      'The phosphate on PEP is transferred to ADP.',
      'The unstable enol product tautomerizes immediately.',
      'Stable pyruvate exits the active site while ATP completes the payoff phase.',
    ],
    energyDelta: { atp: 2, nadh: 0 },
    notes: ['Exit gate of glycolysis', 'Final ATP yield creates net +2 ATP per glucose'],
    regulatory: true,
    articleStepLabel: 'Biology Online Step 9',
    articleSummary: 'Reviewed against the article: pyruvate kinase performs the second substrate-level phosphorylation, yielding pyruvate as the endpoint.',
    repeatCount: 2,
    camera: {
      focus: [0, 0.42, 0],
      offset: [4.8, 5.8, 16.8],
    },
  }),
];

export const glycolysisOutcome = {
  netATP: 2,
  netNADH: 2,
  output: '2 Pyruvate',
};
